apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-on-clouds-deployment
  labels:
    app: cat-on-clouds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-on-clouds
  template:
    metadata:
      labels:
        app: cat-on-clouds
    spec:
      containers:
      - name: cat-on-clouds
        image: taomercy/cat-on-clouds:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 23614
        volumeMounts:
        - mountPath: /data/CatOnClouds
          name: cloud-volume
      volumes:
      - name: cloud-volume
        hostPath:
          path: /data/CatOnClouds
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: cat-on-clouds-svc
  labels:
    app: cat-on-clouds
spec:
  type: NodePort
  selector:
    app: cat-on-clouds
  ports:
    - protocol: TCP
      port: 23614
      targetPort: 23614
      nodePort: 32764
