apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-on-clouds-deployment
  labels:
    app: cat-on-clouds
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat-on-clouds
  template:
    metadata:
      labels:
        app: cat-on-clouds
    spec:
      containers:
      - name: cat-on-clouds
        image: cat-on-clouds:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data/CatOnClouds
          name: test-volume
    volumes:
    - name: test-volume
      hostPath:
        path: /data/CatOnClouds
        type: Directory